### ISSUE TITLE
Pipelines: Add New pipeline for other languages + Improvements to the Pipeline pattern

### ISSUE THREAD

**Issue by timpur** [cdk-cosmos/cosmos#25]
- Static Sites ?
- Java ?
- DotNet ?
- Docker ?

- General Pattern for all these pipelines ?

**Comment by timpur** [comment]
I think we should have a high level base pipeline that has the basic assumptions like "check out code then build" 

Build all tailored pipelines on top of this base ?

**Comment by ruokai-lai** [comment]
feature request: 1. add in props option vpc in AppNodePipeline in building block. I want to be able to create codebuild with vpc access, so that my codebuild can access resource within my vpc).
