### ISSUE TITLE
SSMState not consistent across stages (CodePipeline)

### ISSUE THREAD

**Issue by thomasguerneyiag** [cdk-cosmos/cosmos#306]
Problem: different versions of app build being deployed in different pipeline deploy stages during some pipeline runs

possible interim fixes: 
- manually change ssm parameters to desired version before running pipeline
- run code pipeline all the way through all stages successfully

**Comment by timpur** [comment]
@thomasguerneyiag is this an issue (after discussing) ?

**Comment by thomasguerneyiag** [comment]
This bug was raised because of either a misunderstanding of the intended functionality by a user or because there really is a bug somewhere - I'm not sure which yet. I'm going to lay out the intended functionality here and find out if this is actually what's happening, get feedback from the user, and also just have this info here if anybody else comes across the same issue. 

If the extension template is used for a typical ECS service, it includes SolarSystem stacks that include ECS services. When these stacks are deployed, the service need to know which version to pull and deploy from ECR.

If the APP_BUILD_VERSION environment variable exists in the deploy environment, the CDK will use the value of this variable as the version of the app to pull and deploy from ECR. It will also take this value and use it to update the version state in parameter store (through the Cosmos SsmState construct). However, if the APP_BUILD_VERSION environment variable doesn't exist in the deploy environment, the CDK will instead use the version state in the parameter store (fetched via the Cosmos SsmState construct, which can both set and fetch the state).

The extension template (used for a typical ECS service) comes with two pipelines:
1) app-appname-code-pipeline
2) app-appname-cdk-pipeline

The *-cdk-pipeline deploys all the the stacks in the CDK repo, including the solar-system stacks. It doesn't build code or push images. When this pipeline is run there is generally no APP_BUILD_VERSION variable present and it fetches the version of the app to deploy from the SsmState. 

The *-code-pipeline builds the app, pushes the image to ECR, and exports the version of this newly built image as APP_BUILD_VERSION so the following deploy stages of the pipeline can access this variable. The pipeline then moves on to these deploy stages, which (typically) deploy only the solar system stacks stage-by-stage to different environments (dev, tst, etc). It uses the APP_BUILD_VERSION from the build stage to know which version to deploy.

What I think might be happening is this:

- For arguments sake, this imaginary extension has two environments, Dev and Tst, and the SsmState is "0.1.0" in both Dev and Tst parameter stores 
- *-code-pipeline is run. It reaches the build stage and builds the app and pushes it to ECR and the new version (0.2.0) is exported as APP_BUILD_VERSION. The pipeline reaches the DeployDev stage and deploys the DevSolarSystem using the APP_BUILD_VERSION, so 0.2.0 is deployed and dev SsmState is updated to 0.2.0.
- The pipeline is stopped before it reaches DeployTst.
- The Dev SsmState is now 0.2.0 and the Tst SsmState is now 0.1.0
- *-cdk-pipeline is run - 0.2.0 is deployed to Dev again and 0.1.0 is deployed to Tst again because those are the states in SsmState.

To make all states in sync, if that's what you really want, then either:

1) Run the *-code-pipeline all the way through, deploying the latest version to each environment
2) manually update the SsmStates to the desired version
3) manually pass in APP_BUILD_VERSION with the desired version into the codebuild project deploying the stacks.

**Comment by thomasguerneyiag** [comment]
Closing this as it is intended behaviour
