### ISSUE TITLE
GithubEnterpriseSourceAction detectChanges prop always resolves to true even if false is passed in props.

### ISSUE THREAD

**Issue by thomasguerneyiag** [cdk-cosmos/cosmos#331]
`this.props.detectChanges` is a boolean - so no matter if it is true or false, `DetectChanges: this.props.detectChanges || true` will always resolve to true

Need to replace with `DetectChanges: this.props.detectChanges !== undefined ? this.props.detectChanges : true`

https://github.com/cdk-cosmos/cosmos/blob/bca9e4b507e592578557a2a9c91b20977ffeae66/packages/%40cosmos-building-blocks/pipeline/src/source/github-enterprise-source-action.ts#L107

**Comment by timpur** [comment]
in ts you can do ` this.props.detectChanges ?? true` which is the same as check for undefined or null https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing
