### ISSUE TITLE
ECS Instance and Service Improvements

### ISSUE THREAD

**Issue by jbnaik** [cdk-cosmos/cosmos#8]
- [x] Use spot instances for ECS fleet
- [x] Allow desiredCount to be configures for Instances and Services
- [x] Have good defaults for service placement strategy 
- [ ] Should alb be optional ?
- [x] container Insights + other cluster options. Maybe a pattern is needed for passing props ??
- [x] Health check props + Routing props
- [ ] Ec2 EBS volume encryption ? (Not easily done since snapshot is not encrypted ...)
- [ ] Dain hook SNS Topic encryption ?
- [ ] ELB Enable access log ?

**Comment by timpur** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html

```
"placementStrategy": [
    {
        "field": "attribute:ecs.availability-zone",
        "type": "spread"
    }
]
```
